### ISSUE TITLE
Animation does not move fur

### ISSUE THREAD

**Issue by TerabyteTim** [hecomi/UnityFurURP#3]
I'm trying to get character animation to move the fur from this package - like in the GIF on the readme page with Unity-Chan.

However there are no examples of this in the package, and my animator is not affecting on the fur.

Is there anything special I need to do to setup the fur to respond to animated movement?

**Comment by hecomi** [comment]
Please check `Mover` scene. Only the geometry-based fur supports the fur movement.
- Article (JP): https://tips.hecomi.com/entry/2021/08/14/115756
- Article (EN - auto translated): https://tips-hecomi-com.translate.goog/entry/2021/08/14/115756?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=nui

**Comment by TerabyteTim** [comment]
Thanks so much! I was using the fin shader - switching to geometry fixed it.
